In [1]:
import numpy as np
import sys
import time 

In [2]:
#size analysis 

In [3]:
arr_list=(range(100000))
arr_array=np.array(arr_list)
print(sys.getsizeof(arr_list))
print(arr_array.nbytes)

48
800000


In [4]:
#time analysis 

In [5]:
start=time.time()
arr2=(i**2 for i in arr_list)
end=time.time()
print(end-start)
start=time.time()
arr3=arr_array**2
end=time.time()
print(end-start)


8.702278137207031e-05
0.00039196014404296875


In [6]:
#basics information about array 

In [7]:
print(arr3.shape)
arr4=np.array([[1,2,3],[1,2,3]])
print(arr4.shape)
print(arr4.size)
print(arr4.ndim)
print(arr4.dtype)

(100000,)
(2, 3)
6
2
int64


In [8]:
#making numpy quick arrays

In [9]:
zero=np.zeros((2,3),dtype='int64')
one=np.ones((2,3))
print(zero)
print(one)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
fullarray=np.full((2,3),100)
print(fullarray)

[[100 100 100]
 [100 100 100]]


In [11]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
ranger=np.arange(1,10,2)
print(ranger)

[1 3 5 7 9]


In [13]:
equals=np.linspace(1,100,5)
print(equals)

[  1.    25.75  50.5   75.25 100.  ]


In [14]:
#getting properties of numpy array

In [15]:
newarray=np.array([[1,2,3,4],[1,2,3,4]])
print(newarray.shape)
print(newarray.size)
print(newarray.dtype)
print(newarray.ndim)

(2, 4)
8
int64
2


In [16]:
#operations on numpy array

In [17]:
reshape=newarray.reshape((4,2))
print(reshape)
flat=newarray.flatten()
print(flat)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[1 2 3 4 1 2 3 4]


In [18]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.dtype)
arr=arr.astype(np.int8)
print(arr.dtype)


int64
int8


In [19]:
#fancy indexing and boolean indexing 

In [20]:
arr4=np.array([1,2,3,4,5,6,7,8])
idx=[0,1,5]
print(arr4[[idx]])
print(arr4[arr4%2==0])

[[1 2 6]]
[2 4 6 8]


In [21]:
#slicing 

In [22]:
slice1d=arr4[1:5:2]
print(slice1d)
sliced=newarray[0:2,0:2]
print(sliced)

[2 4]
[[1 2]
 [1 2]]


In [23]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.sum())
print(arr.prod())
print(arr.min())
print(arr.max())
print(arr.argmin())
print(arr.argmax())

36
40320
1
8
0
7


In [24]:
#3d arrays 

In [25]:
import numpy as np

arr3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
print(arr3d.sum(axis=2))
print(arr3d.prod(axis=0))
print(arr3d.min(axis=2))
print(arr3d.max(axis=1))
print(arr3d.argmin())
print(arr3d.argmax())

[[ 3  7]
 [11 15]]
[[ 5 12]
 [21 32]]
[[1 3]
 [5 7]]
[[3 4]
 [7 8]]
0
7


In [27]:
#slicing 3d array 

In [28]:
sliced3d=arr3d[1:2,1:2,1:2]
print(sliced3d)

[[[8]]]


In [29]:
#vectorisation and broad casting 

In [32]:
arr4=arr4+5
arr4
arr4=arr4+[5]
arr4

array([11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
#some other functions of np array

In [34]:
print(np.unique(arr4))
print(np.sort(arr4))
print(np.abs(arr4))

[11 12 13 14 15 16 17 18]
[11 12 13 14 15 16 17 18]
[11 12 13 14 15 16 17 18]
